import { PREVIEW } from '../editor/templates/templateImages'
import {
  sharedCss,
  landingHtml,
  saasHtml,
  portfolioHtml,
  agencyHtml,
  restaurantHtml,
  blogHtml,
  ecommerceHtml,
  travelHtml,
  fitnessHtml,
} from '../editor/templates/templateContent'

export const PREBUILT_TEMPLATES = [
  {
    id: 'blank',
    name: 'Blank Canvas',
    description: 'Start from scratch with an empty canvas',
    previewImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=250&fit=crop',
    editor: 'grapesjs',
    projectData: {},
    html: '',
    css: '',
    category: 'General',
    sections: 0,
    darkMode: true,
  },
  {
    id: 'landing',
    name: 'Landing Page',
    description: 'Hero with dashboard image, features, testimonials & CTA',
    previewImage: PREVIEW.landing,
    editor: 'grapesjs',
    projectData: {},
    html: landingHtml,
    css: sharedCss,
    category: 'Landing',
    sections: 5,
    darkMode: false,
    badge: 'Popular',
  },
  {
    id: 'saas-landing',
    name: 'SaaS Website',
    description: 'Product shots, feature section, pricing cards',
    previewImage: PREVIEW.saas,
    editor: 'grapesjs',
    projectData: {},
    html: saasHtml,
    css: sharedCss,
    category: 'SaaS',
    sections: 4,
    darkMode: true,
    badge: 'New',
  },
  {
    id: 'minimal-portfolio',
    name: 'Portfolio',
    description: 'Profile photo + 6-project image gallery',
    previewImage: PREVIEW.portfolio,
    editor: 'grapesjs',
    projectData: {},
    html: portfolioHtml,
    css: sharedCss,
    category: 'Portfolio',
    sections: 3,
    darkMode: true,
    badge: 'Trending',
  },
  {
    id: 'agency',
    name: 'Agency Website',
    description: 'Full-bleed hero, services, team headshots',
    previewImage: PREVIEW.agency,
    editor: 'grapesjs',
    projectData: {},
    html: agencyHtml,
    css: sharedCss,
    category: 'Agency',
    sections: 4,
    darkMode: true,
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    description: 'Food hero, dish photos with prices, reservations',
    previewImage: PREVIEW.restaurant,
    editor: 'grapesjs',
    projectData: {},
    html: restaurantHtml,
    css: sharedCss,
    category: 'Restaurant',
    sections: 3,
    darkMode: true,
  },
  {
    id: 'blog',
    name: 'Blog',
    description: 'Featured post banner + 3 article cards with images',
    previewImage: PREVIEW.blog,
    editor: 'grapesjs',
    projectData: {},
    html: blogHtml,
    css: sharedCss,
    category: 'Blog',
    sections: 3,
    darkMode: false,
  },
  {
    id: 'ecommerce',
    name: 'Ecommerce Homepage',
    description: 'Promo banner, 4 product cards with photos & prices',
    previewImage: PREVIEW.ecommerce,
    editor: 'grapesjs',
    projectData: {},
    html: ecommerceHtml,
    css: sharedCss,
    category: 'E-commerce',
    sections: 3,
    darkMode: false,
  },
  {
    id: 'travel',
    name: 'Travel & Resort',
    description: 'Beach hero, room photos, booking CTA',
    previewImage: PREVIEW.travel,
    editor: 'grapesjs',
    projectData: {},
    html: travelHtml,
    css: sharedCss,
    category: 'Travel',
    sections: 4,
    darkMode: false,
  },
  {
    id: 'fitness',
    name: 'Fitness Gym',
    description: 'Bold gym hero, membership plans, member review',
    previewImage: PREVIEW.fitness,
    editor: 'grapesjs',
    projectData: {},
    html: fitnessHtml,
    css: sharedCss,
    category: 'Fitness',
    sections: 3,
    darkMode: true,
    badge: 'Trending',
  },
]

export function getTemplateById(id) {
  return PREBUILT_TEMPLATES.find((t) => t.id === id) || PREBUILT_TEMPLATES[0]
}
