export interface SmsProviderSendResult {
  success: boolean;
  providerRequestId?: string;
  error?: string;
}

export interface SmsProviderVerifyResult {
  success: boolean;
  error?: string;
}

export interface SmsProviderContext {
  campaignId: number;
  campaignName: string;
  visitId?: number | null;
  variables?: Record<string, string | undefined>;
}

export interface SmsProvider {
  /**
   * Sends an OTP to the given phone number.
   * For Local OTP, the OTP is generated by our system and passed here.
   * For Partner OTP, the partner generates the OTP, so otp can be ignored or empty.
   */
  sendOtp(
    phone: string,
    otp: string,
    config: any,
    context: SmsProviderContext,
  ): Promise<SmsProviderSendResult>;

  /**
   * Optional verification endpoint.
   * Used for Partner API Mode where telecom operators verify the OTP themselves.
   */
  verifyOtp?(
    phone: string,
    otp: string,
    providerRequestId: string,
    config: any,
  ): Promise<SmsProviderVerifyResult>;
}
